spring:
  datasource:
    url: jdbc:mysql://101.201.254.85:3306/task_center?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
  mail:
    host: smtp.qq.com
    username: 1029598070@qq.com
    password: gljdclohnltubbed
    protocol: smtp


server:
  port: 8001
  tomcat:
    basedir: /tmp/tomcat
  servlet:
    context-path: /task-center

mybatis:
  mapper-locations: classpath:com/huangjiang/task-center/orm/mapper/*.xml
  type-aliases-package: com.huangjiang.taskcenter.orm.entity

